kind: pipeline
name: default

steps:
- name: edgar
  image: golang:1.11
  commands:
  - export DIR=$GOPATH/src/github.com/tmlbl/edgar
  - mkdir -p $DIR
  - cp -r . $DIR
  - cd $DIR
  - go get ./...
  - go test -v
